### ISSUE TITLE
No Graph

### ISSUE THREAD

**Issue by BerniGR** [abhinav-adtechs/PanTompkins#1]
Could you fix that this app shows a signal 
It doesnt show anything 

Thank you!

**Comment by abhinav-adtechs** [comment]
@BerniGR it does show a chart, anyhow I'll test it again. 
Also, can you please provide me your voltage readings at 200 samples per sec? I'll test it against your readings and update the code.

**Comment by abhinav-adtechs** [comment]
Also keep in mind the location of the file --> 
Change it at root-> MainActivity.java -> line 105

**Comment by BerniGR** [comment]
But where is the data.csv ?
I have a question about the "HeartyFilter.java" it is never used ?

Thank you!

**Comment by abhinav-adtechs** [comment]
data.csv file is not attached anywhere in the project. 
HeartyFilter is not used in this project. It was used earlier to test the implementation by other developer.
