### ISSUE TITLE
Data File missing

### ISSUE THREAD

**Issue by rachith** [abhinav-adtechs/PanTompkins#2]
Please provide the data.csv file.

**Comment by abhinav-adtechs** [comment]
Hi! The company I was working for had actual data file of a patient and thus I'm not open to share that. Feel free to test with a sample data file and raise a PR!

Thanks.

**Comment by rachith** [comment]
1) How you are getting or building the data.csv file. IS it from the ECG data QRS peaks  
and please provide the data value unit.
2) I am working on heart beat value detection from the ECG data, can it be possible with this code.

**Comment by abhinav-adtechs** [comment]
The file should have **voltage** data of the ECG value sampled at 200 samples per second (check code, could be 250 or something) 
So the code does a lot of things like QRS detection and all intermediate steps involved in Pan Tompkins  algorithm. 
This code can be used to get the heart beat value from the ECG data as well.

**Comment by rachith** [comment]
Thank You.

**Comment by rachith** [comment]
![sample](https://user-images.githubusercontent.com/10695526/43463037-46e8c244-94f5-11e8-8692-642311f7d9ff.PNG)
The samplingRate is not used in the code.
